version: "3.9"

services:
    backend:
        build: .
        container_name: medical-events-backend
        env_file:
            - .env
        expose:
            - "8000"
        restart: unless-stopped

    nginx:
        build:
            context: ./nginx
        container_name: medical-events-nginx
        ports:
            - "80:80"
        depends_on:
            - backend
        restart: unless-stopped