# Generated by Django 6.0.2 on 2026-02-28 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("photo_url", models.URLField()),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Card",
                "verbose_name_plural": "Cards",
                "db_table": "cards",
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Specialty",
                "verbose_name_plural": "Specialties",
                "db_table": "specialties",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("location", models.CharField(max_length=200)),
                ("duration", models.DurationField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("online", "Онлайн"),
                            ("offline", "Офлайн"),
                            ("mixed", "Змішаний"),
                        ],
                        default="offline",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("done", "Done"),
                            ("canceled", "Canceled"),
                        ],
                        default="planned",
                        max_length=10,
                    ),
                ),
                (
                    "card_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.card",
                    ),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        related_name="events", to="events.specialty"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["scheduled_date", "scheduled_time"],
            },
        ),
    ]
