# Generated by Django 6.0.2 on 2026-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="form_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
