# Generated by Django 6.0.2 on 2026-03-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_form_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"verbose_name": "Карточка", "verbose_name_plural": "Карточки"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["scheduled_date", "scheduled_time"],
                "verbose_name": "Подія",
                "verbose_name_plural": "Події",
            },
        ),
        migrations.AlterModelOptions(
            name="specialty",
            options={
                "verbose_name": "Спеціальність",
                "verbose_name_plural": "Спеціальності",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("запланований", "Запланований"),
                    ("завершений", "Завершений"),
                    ("відмінений", "Відмінений"),
                ],
                default="запланований",
                max_length=12,
            ),
        ),
    ]
