# Generated by Django 6.0.2 on 2026-03-17 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_card_options_alter_event_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="card_id",
        ),
        migrations.AddField(
            model_name="event",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.card",
                verbose_name="Карточка",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="event",
            name="duration",
            field=models.DurationField(verbose_name="Тривалість"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("online", "Онлайн"),
                    ("offline", "Офлайн"),
                    ("mixed", "Змішаний"),
                ],
                default="offline",
                max_length=10,
                verbose_name="Тип події",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="form_url",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Посилання на гугл-форму",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=200, verbose_name="Місце проведення"),
        ),
        migrations.AlterField(
            model_name="event",
            name="scheduled_date",
            field=models.DateField(verbose_name="Дата проведення"),
        ),
        migrations.AlterField(
            model_name="event",
            name="scheduled_time",
            field=models.TimeField(verbose_name="Час проведення"),
        ),
        migrations.AlterField(
            model_name="event",
            name="specialties",
            field=models.ManyToManyField(
                related_name="events",
                to="events.specialty",
                verbose_name="Спеціальності",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("запланований", "Запланований"),
                    ("завершений", "Завершений"),
                    ("відмінений", "Відмінений"),
                ],
                default="запланований",
                max_length=12,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Назва"),
        ),
    ]
