# Generated by Django 6.0.2 on 2026-03-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_event_card_id_event_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="form_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Посилання на гугл-форму"
            ),
        ),
    ]
