# Generated by Django 6.0.2 on 2026-03-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_form_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="photo_url",
            field=models.URLField(verbose_name="Посилання на зображення"),
        ),
        migrations.AlterField(
            model_name="card",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="card",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Назва"),
        ),
    ]
