# Generated by Django 6.0.2 on 2026-03-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_card_photo_url_alter_card_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialty",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
        ),
    ]
